#!/bin/bash
#
# ===========================================
# MultiVPN - Auto Start
# ===========================================
# 
# Desc: script used to enable vpn on reboot, 
# this is part of multivpn service.
#
# ----------------------------------
# Auto Start
# ----------------------------------
ROOT=/etc/openvpn
[[ ! -f $ROOT/multivpn/.enabled ]] && exit 0
for vpn in $(cat $ROOT/multivpn/.enabled); do
        source $ROOT/$vpn/.vars
        if ! ps -ef | grep "[o]penvpn --cd $ROOT/$vpn" &>/dev/null; then
                openvpn --cd $ROOT/$vpn --script-security $security --daemon \
                        --config $ROOT/$vpn/openvpn.conf &>/dev/null
        fi
done
