#!/bin/bash

NORMAL='\033[0m'
YELLOW='\033[1;33m'

clear; echo -e ${YELLOW}
echo -e "
 __  __         _  _    _  __     __ ____   _   _ 
|  \/  | _   _ | || |_ (_) \ \   / /|  _ \ | \ | |
| |\/| || | | || || __|| |  \ \ / / | |_) ||  \| |
| |  | || |_| || || |_ | |   \ V /  |  __/ | |\  |
|_|  |_| \__,_||_| \__||_|    \_/   |_|    |_| \_|
"
echo -e "\n${NORMAL}MultiVPN Server Generator - Version 1.0"
echo -e "${YELLOW}======================================================${NORMAL}"
echo -e "\nSERVER: $(hostname)\n"
echo -e "${YELLOW}======================================================${NORMAL}"
echo -e "Executing at $(date +%d-%m-%y\ %H:%M)"
sleep 1
